In [1]:
import numpy as np
from scipy.optimize import minimize
import matplotlib.pyplot as plt
import itertools
import pandas as pd
import scipy
from tqdm.notebook import tqdm  
import zipfile
import numpy as np
from scipy import stats


In [2]:
p = pd.read_csv("Folder1-Parameter_Fits/all_viruses_best_fits.csv").iloc[0, -3]
p

np.float64(0.9997023665595954)

In [3]:
file_path = "Folder2-MCMC_Outputs/model_MCMC_Raw.npy.zip"

with zipfile.ZipFile(file_path) as zip_ref: 
    file_list = zip_ref.namelist()
    with zip_ref.open(file_list[0]) as npy_file:
        data = np.load(npy_file)
model_params = data[0][:,0]


file_path = "Folder2-MCMC_Outputs/ss_model_MCMC_Raw.npy.zip"

with zipfile.ZipFile(file_path) as zip_ref: 
    file_list = zip_ref.namelist()
    with zip_ref.open(file_list[0]) as npy_file:
        data = np.load(npy_file)
ss_params = data.T

ss_params



array([[0.6699705 , 0.71257588, 0.67992243, 0.21404711],
       [0.6699705 , 0.71257588, 0.67992243, 0.21404711],
       [0.6699705 , 0.71257588, 0.67992243, 0.21404711],
       ...,
       [0.68003792, 0.68718257, 0.71408981, 0.199693  ],
       [0.68003792, 0.68718257, 0.71408981, 0.199693  ],
       [0.68003792, 0.68718257, 0.71408981, 0.199693  ]],
      shape=(1000000, 4))

In [4]:
model_params

array([0.99970299, 0.99970299, 0.99970299, ..., 0.9996995 , 0.9996995 ,
       0.9996995 ], shape=(1000000,))

In [5]:

train_data = np.array([1,.68,.48,.32,.07])
train_data = train_data/np.sum(train_data)
train_data


array([0.39215686, 0.26666667, 0.18823529, 0.1254902 , 0.02745098])

In [6]:
# Gene orders of variants from 2 datasets with DOIs
pmg_combos = np.array([[1,2,3,4,5],[1,4,2,3,5],[1,3,4,2,5],[1,4,3,2,5],[1,2,4,3,5],[1,3,2,4,5]]) # 10.1128/jvi.73.6.4705-4712.1999
ng_combos = np.array([[1,2,3,4,5],[2, 3, 4, 1, 5], [4,1,2,3,5], [4,2,3,1,5]]) # 10.1128/jvi.74.17.7895-7902.2000





In [7]:
# set genome positions for each variant
gene_lengths = np.array([1325, 813, 830, 1664, 6372])

pmg_lenpos = []
for pos_pre in pmg_combos:
    pos = pos_pre
    gene_len_temp = [gene_lengths[i-1] for i in pos]
    genome_pos = [np.sum(gene_len_temp[0:i]) + (i-1) * 10 for i in pos]
    genome_pos = np.array(genome_pos - np.min(genome_pos))
    pmg_lenpos.append(genome_pos)
    
ng_lenpos = []
for pos_pre in ng_combos:
    pos = pos_pre
    gene_len_temp = [gene_lengths[i-1] for i in pos]
    genome_pos = [np.sum(gene_len_temp[0:i]) + (i-1) * 10 for i in pos]
    genome_pos = np.array(genome_pos - np.min(genome_pos))
    ng_lenpos.append(genome_pos)

    

In [8]:
ng_data = np.array([[0.282, 0.195, 0.252, 0.251, 0.02 ],
                    [0.162, 0.118, 0.135, 0.578, 0.007],
                    [0.151, 0.271, 0.354, 0.21 , 0.014],
                    [0.108, 0.182, 0.284, 0.415, 0.011]])

In [9]:
all_ng_preds = []
p = model_params
ng_RAM_preds = [ ]
for i in range(0, ng_data.shape[0]):
    labmda_pred = np.array([p**x for x in ng_lenpos[i]])
    labmda_pred = labmda_pred/labmda_pred.sum(axis=0)
    ng_RAM_preds.append(labmda_pred)
ng_RAM_preds = np.array(ng_RAM_preds)
ng_RAM_preds.mean(axis=2)

array([[0.3545783 , 0.27767493, 0.21635975, 0.1315999 , 0.01978713],
       [0.29741501, 0.18089329, 0.12168476, 0.38170943, 0.01829751],
       [0.15363778, 0.37431686, 0.2517742 , 0.19717273, 0.02309843],
       [0.14324219, 0.27329308, 0.21294553, 0.34898281, 0.02153639]])

In [10]:
#arr = np.array([[1, 2], [3, 4], [5, 6]])
value_to_add = [1] * ss_params.shape[0]  # Must have same number of elements as rows
p = np.insert(ss_params, 0, value_to_add, axis=1)
p = np.cumprod(p, axis =1)
p = p.T/np.sum(p, axis = 1)
ng_ss_preds = p.T
ng_ss_preds = ng_ss_preds[:,ng_combos-1]
ng_ss_preds.shape

(1000000, 4, 5)

In [11]:
pmg_data = np.array([[100, 81.5, 73.0, 58.8 ,2.6],
                     [100, 53.3, 97.1, 87.1, 4.1],
                     [100, 75.3, 78.5, 99, 4.7],
                     [100, 57.5, 71.6, 99, 1.7],
                     [100, 89.1, 70.1, 92.5, 2.9],
                     [100, 74.9, 99, 70.7, 3.4]]).T
pmg_data = (pmg_data/np.sum(pmg_data, axis = 0)).T
pmg_data


array([[0.31655587, 0.25799304, 0.23108579, 0.18613485, 0.00823045],
       [0.29274005, 0.15603044, 0.28425059, 0.25497658, 0.01200234],
       [0.27972028, 0.21062937, 0.21958042, 0.27692308, 0.01314685],
       [0.30321407, 0.17434809, 0.21710127, 0.30018193, 0.00515464],
       [0.2820079 , 0.25126904, 0.19768754, 0.2608573 , 0.00817823],
       [0.28735632, 0.21522989, 0.28448276, 0.20316092, 0.00977011]])

In [12]:
value_to_add = [1] * ss_params.shape[0]  
p = np.insert(ss_params, 0, value_to_add, axis=1)
p = np.cumprod(p, axis =1)
p = p.T/np.sum(p, axis = 1)
pmg_ss_preds = p.T
pmg_ss_preds = pmg_ss_preds[:,pmg_combos-1]
pmg_ss_preds.shape


(1000000, 6, 5)

In [13]:
all_pmg_preds = []
p = model_params
pmg_RAM_preds = [ ]
for i in range(0, pmg_data.shape[0]):
    labmda_pred = np.array([p**x for x in pmg_lenpos[i]])
    labmda_pred = labmda_pred/labmda_pred.sum(axis=0)
    pmg_RAM_preds.append(labmda_pred)
pmg_RAM_preds = np.array(pmg_RAM_preds)
pmg_RAM_preds.mean(axis=2)

array([[0.3545783 , 0.27767493, 0.21635975, 0.1315999 , 0.01978713],
       [0.39818211, 0.14777816, 0.24216961, 0.18965189, 0.02221822],
       [0.37313261, 0.17682879, 0.13848451, 0.29073229, 0.0208218 ],
       [0.39856285, 0.14791943, 0.18887712, 0.24240114, 0.02223945],
       [0.37225141, 0.29151412, 0.13815756, 0.17730424, 0.02077267],
       [0.35507499, 0.21666277, 0.27666324, 0.13178418, 0.01981482]])

In [43]:
pmg_means_ss = np.mean(pmg_ss_preds.T, axis = 2).T
pmg_means_RAM = np.mean(pmg_RAM_preds, axis = 2)
ng_means_ss = np.mean(ng_ss_preds.T, axis = 2).T
ng_means_RAM = np.mean(ng_RAM_preds, axis = 2)
mae_RAM = np.abs(ng_means_RAM - ng_data) 
mae_ss = np.abs(ng_means_ss - ng_data)
mae_ss = list(mae_ss) + list(np.abs(pmg_means_ss - pmg_data))
mae_RAM = list(mae_RAM) + list(np.abs(pmg_means_RAM - pmg_data))
print(np.mean(mae_ss))
print(np.mean(mae_RAM))

0.054478546112697944
0.05006048348746266


In [28]:
variants = ["NPMGL (WT)", "NMGPL", "NGPML", "NGMPL", "NPGML", "NMPGL"] 
variants += ["NPMGL (WT)", "GNPML", "PMGNL", "GPMNL"]
Dataset_DOIs = ["10.1128/jvi.73.6.4705-4712.1999"] * 6 + ["10.1128/jvi.74.17.7895-7902.2000"] * 4


data_df = pd.DataFrame(list(pmg_data) + list(ng_data))

data_df = pd.concat([pd.DataFrame(variants), data_df, pd.DataFrame(Dataset_DOIs)], axis = 1)

data_df.columns = ["Variant", "N", "P", "M", "G", "L", "Dataset"]

data_df.to_csv("Folder3-Gene_Shuffle_Predictions/prot_expression_ratio_data.csv")


In [94]:
pmg_means_ss = np.mean(pmg_ss_preds.T, axis = 2).T
pmg_means_RAM = np.mean(pmg_RAM_preds, axis = 2)
ng_means_ss = np.mean(ng_ss_preds.T, axis = 2).T
ng_means_RAM = np.mean(ng_RAM_preds, axis = 2)
pmg_std_ss = np.std(pmg_ss_preds.T, axis = 2).T
pmg_std_RAM = np.std(pmg_RAM_preds, axis = 2)
ng_std_ss = np.std(ng_ss_preds.T, axis = 2).T
ng_std_RAM = np.std(ng_RAM_preds, axis = 2)

preds_df = pd.DataFrame(list(pmg_means_RAM) + list(ng_means_RAM))
preds_df = pd.concat([pd.DataFrame(variants),preds_df], axis = 1)
preds_df.columns = ["Variant", "N", "P", "M", "G", "L"]
preds_df
preds_df.to_csv("Folder3-Gene_Shuffle_Predictions/RAM_mean_predictions.csv")

preds_df = pd.DataFrame(list(pmg_means_ss) + list(ng_means_ss))
preds_df = pd.concat([pd.DataFrame(variants),preds_df], axis = 1)
preds_df.columns = ["Variant", "N", "P", "M", "G", "L"]
preds_df
preds_df.to_csv("Folder3-Gene_Shuffle_Predictions/ss_mean_predictions.csv")


preds_df = pd.DataFrame(list(pmg_std_RAM) + list(ng_std_RAM))
preds_df = pd.concat([pd.DataFrame(variants),preds_df], axis = 1)
preds_df.columns = ["Variant", "N", "P", "M", "G", "L"]
preds_df
preds_df.to_csv("Folder3-Gene_Shuffle_Predictions/RAM_std_predictions.csv")

preds_df = pd.DataFrame(list(pmg_std_ss) + list(ng_std_ss))
preds_df = pd.concat([pd.DataFrame(variants),preds_df], axis = 1)
preds_df.columns = ["Variant", "N", "P", "M", "G", "L"]
preds_df
preds_df.to_csv("Folder3-Gene_Shuffle_Predictions/ss_std_predictions.csv")

# --- Build MAE matrices (variants x 5 genes) ---
mae_RAM_mat = np.vstack([
    np.abs(ng_means_RAM - ng_data),
    np.abs(pmg_means_RAM - pmg_data),
])

mae_ss_mat = np.vstack([
    np.abs(ng_means_ss - ng_data),
    np.abs(pmg_means_ss - pmg_data),
])

# --- Gene identity vector matching flattened arrays ---
genes = np.array(["N", "P", "M", "G", "L"])
gene_ids = np.tile(genes, mae_RAM_mat.shape[0])

# --- Flatten errors ---
abs_err_RAM = mae_RAM_mat.ravel()
abs_err_ss  = mae_ss_mat.ravel()


error_df = pd.DataFrame({
    "Model": ["RAM"] * len(abs_err_RAM) + ["Stop-Start"] * len(abs_err_ss),
    "Absolute_Error": np.concatenate([abs_err_RAM, abs_err_ss]),
    "Gene": np.concatenate([gene_ids, gene_ids])
})

error_df.to_csv("Folder3-Gene_Shuffle_Predictions/model_absolute_errors.csv",
                index=False)